export const PRODUCTS = [
  {
    id: 1,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 2,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Out Of Stock",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 3,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 4,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 5,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 6,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 7,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 8,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 9,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
  {
    id: 10,
    name: "Bathroom Wash basing",
    description: "Titanium En filed Wash basing for Mo...",
    price: "100 USD",
    status: "Balanced",
    minThreshold: "1500 Pcs",
    currentStock: "2000 Pcs",
    lastUpdated: "Jan 12. 2023 3:40 PM",
  },
];
